[
  {
    "cmd": [
      "git",
      "-c",
      "core.quotePath=false",
      "checkout",
      "HEAD~",
      "--",
      "DEPS"
    ],
    "cwd": "[CACHE]/src",
    "infra_step": true,
    "name": "checkout the previous DEPS"
  },
  {
    "cmd": [
      "python",
      "-u",
      "RECIPE_REPO[depot_tools]/gclient.py",
      "recurse",
      "RECIPE_MODULE[depot_tools::gclient]/resources/diff_deps.py"
    ],
    "cwd": "[CACHE]/src",
    "env_suffixes": {
      "PATH": [
        "RECIPE_REPO[depot_tools]"
      ]
    },
    "infra_step": true,
    "name": "gclient recursively git diff all DEPS",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@raw_io.output_text@fatal: bad object abcdef1234567890@@@",
      "@@@STEP_LOG_END@raw_io.output_text@@@",
      "@@@STEP_LOG_LINE@DepsDiffException@Couldn't checkout previous ref: fatal: bad object abcdef1234567890@@@",
      "@@@STEP_LOG_END@DepsDiffException@@@"
    ]
  },
  {
    "cmd": [
      "git",
      "-c",
      "core.quotePath=false",
      "checkout",
      "HEAD",
      "--",
      "DEPS"
    ],
    "cwd": "[CACHE]/src",
    "infra_step": true,
    "name": "checkout the original DEPS"
  },
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/engine.py\", in run_steps",
      "    raw_result = recipe_obj.run_steps(api, engine)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/recipe_deps.py\", in run_steps",
      "    properties_def, api=api)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", in invoke_with_properties",
      "    arg_names, **additional_args)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", in _invoke_with_properties",
      "    return callable_obj(*props, **additional_args)",
      "  File \"RECIPE_REPO[depot_tools]/recipes/recipe_modules/gclient/tests/diff_deps.py\", line 33, in RunSteps",
      "    affected_files = api.gclient.diff_deps(api.path['cache'])",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/recipe_api.py\", in _inner",
      "    return func(*a, **kw)",
      "  File \"RECIPE_REPO[depot_tools]/recipes/recipe_modules/gclient/api.py\", line 398, in diff_deps",
      "    raise self.DepsDiffException(msg)",
      "DepsDiffException: Couldn't checkout previous ref: fatal: bad object abcdef1234567890"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: DepsDiffException(\"Couldn't checkout previous ref: fatal: bad object abcdef1234567890\",)"
    },
    "name": "$result"
  }
]